export const INTERVIEW_REPOSITORY = Symbol('INTERVIEW_REPOSITORY');
export const MESSAGE_REPOSITORY = Symbol('MESSAGE_REPOSITORY');
export const INTERVIEW_QUESTION_REPOSITORY = Symbol(
  'INTERVIEW_QUESTION_REPOSITORY',
);
